import { StyleSheet } from 'react-native';
import { Colors } from '../theme/colors';

const styles = StyleSheet.create({
  main: {
    flex: 1,
  },
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: Colors.backgroundColor,
  },
  mainContent: {
    flex: 1,
    padding: 0,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    color: '#dcddde',
    fontSize: 18,
    marginBottom: 20,
  },
  backButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 4,
  },
  backButtonText: {
    color: Colors.white,
    fontWeight: 'bold',
  },
  header: {
    backgroundColor: Colors.backgroundColor,
    borderBottomWidth: 1,
    borderBottomColor: '#202225',
    paddingBottom: 0,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  headerContent: {
    paddingHorizontal: 16,
  },
  workspaceAvatarContainer: {
    position: 'relative',
    alignItems: 'center',
    marginBottom: 12,
  },
  workspaceAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#2f3136',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  workspaceAvatarText: {
    color: Colors.white,
    fontSize: 32,
    fontWeight: 'bold',
  },
  badgeContainer: {
    position: 'absolute',
    bottom: 0,
    right: '40%',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: Colors.backgroundColor,
  },
  statusBadgeText: {
    color: Colors.white,
    fontSize: 10,
    fontWeight: 'bold',
  },
  workspaceInfoContainer: {
    alignItems: 'center',
    marginBottom: 16,
  },
  workspaceName: {
    color: Colors.white,
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 8,
    textAlign: 'center',
  },
  workspaceDescription: {
    color: '#dcddde',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  workspaceStats: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 16,
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 10,
  },
  statText: {
    color: '#8e9297',
    fontSize: 12,
    marginLeft: 4,
  },
  headerActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingBottom: 16,
  },
  inviteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  inviteButtonText: {
    color: Colors.white,
    marginLeft: 8,
    fontWeight: 'bold',
    fontSize: 14,
  },
  tabsContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.backgroundColor,
    paddingTop: 0,
    paddingBottom: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#202225',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  tab: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    position: 'relative',
  },
  tabContent: {
    alignItems: 'center',
  },
  activeTab: {
    backgroundColor: 'transparent',
  },
  activeTabIndicator: {
    position: 'absolute',
    bottom: 0,
    height: 3,
    width: '50%',
    backgroundColor: Colors.primary,
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
  },
  tabText: {
    color: '#8e9297',
    marginTop: 4,
    fontSize: 12,
    fontWeight: '500',
  },
  activeTabText: {
    color: Colors.primary,
    fontWeight: 'bold',
  },
  actionBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#2f3136',
    borderBottomWidth: 1,
    borderBottomColor: '#202225',
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#40444b',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 20,
    marginRight: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 1,
  },
  searchInput: {
    flex: 1,
    color: '#dcddde',
    marginLeft: 8,
    fontSize: 14,
  },
  actionButtonContainer: {
    flexDirection: 'row',
  },
  addButton: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  addButtonText: {
    color: Colors.white,
    marginTop: 4,
    fontSize: 12,
    fontWeight: 'bold',
  },
  contentContainer: {
    flex: 1,
    backgroundColor: Colors.backgroundColor,
  },
  listContent: {
    padding: 16,
  },
  channelCard: {
    flexDirection: 'row',
    backgroundColor: '#2f3136',
    borderRadius: 12,
    marginBottom: 12,
    marginHorizontal: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  channelIconContainer: {
    width: 70,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#202225',
    paddingVertical: 16,
  },
  channelIconBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  channelContent: {
    flex: 1,
    padding: 12,
    justifyContent: 'space-between',
  },
  channelTitle: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  channelDescription: {
    color: '#8e9297',
    fontSize: 13,
    marginBottom: 8,
  },
  channelMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  channelMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  channelMetaText: {
    color: '#8e9297',
    fontSize: 12,
    marginLeft: 4,
  },
  channelJoinButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(114, 137, 218, 0.1)',
  },
  channelJoinText: {
    color: Colors.primary,
    fontSize: 12,
    fontWeight: 'bold',
    marginRight: 2,
  },
  memberCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2f3136',
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 12,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  memberAvatarContainer: {
    position: 'relative',
    marginRight: 12,
  },
  memberAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
  },
  memberAvatarText: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: 'bold',
  },
  statusIndicator: {
    position: 'absolute',
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#2f3136',
    bottom: -2,
    right: -2,
  },
  memberInfo: {
    flex: 1,
  },
  memberNameContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  memberName: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 8,
  },
  memberRoleBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
  },
  memberRoleText: {
    color: Colors.white,
    fontSize: 10,
    fontWeight: 'bold',
  },
  memberStatusText: {
    color: '#8e9297',
    fontSize: 13,
  },
  memberActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  memberActionButton: {
    padding: 8,
    marginLeft: 4,
  },
  settingsContainer: {
    padding: 16,
  },
  settingsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#202225',
    backgroundColor: '#2f3136',
    marginBottom: 16,
  },
  settingsHeaderTitle: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  settingSection: {
    marginBottom: 24,
    paddingHorizontal: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  settingSectionTitle: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  settingCard: {
    backgroundColor: '#2f3136',
    borderRadius: 12,
    overflow: 'hidden',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  settingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
  },
  settingDivider: {
    height: 1,
    backgroundColor: '#40444b',
    marginHorizontal: 16,
  },
  settingLabel: {
    color: Colors.white,
    fontSize: 15,
    fontWeight: '500',
  },
  settingSubLabel: {
    color: '#8e9297',
    fontSize: 13,
    marginTop: 4,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginLeft: 16,
  },
  settingInput: {
    backgroundColor: '#40444b',
    color: '#dcddde',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    flex: 1,
  },
  inputIcon: {
    marginLeft: 8,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  settingDropdown: {
    backgroundColor: '#40444b',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  dropdownText: {
    color: '#dcddde',
    marginRight: 8,
    fontSize: 14,
  },
  visibilityOptions: {
    flexDirection: 'row',
    marginTop: 8,
  },
  visibilityOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#40444b',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginRight: 12,
  },
  selectedVisibility: {
    backgroundColor: Colors.primary,
  },
  visibilityText: {
    color: '#8e9297',
    marginLeft: 8,
    fontSize: 14,
  },
  selectedVisibilityText: {
    color: Colors.white,
  },
  dangerCard: {
    backgroundColor: 'rgba(237, 66, 69, 0.1)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(237, 66, 69, 0.3)',
    overflow: 'hidden',
  },
  dangerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
  },
  dangerItemTitle: {
    color: '#ed4245',
    fontSize: 15,
    fontWeight: 'bold',
  },
  dangerItemDescription: {
    color: '#dcddde',
    fontSize: 13,
    marginTop: 4,
    maxWidth: '85%',
  },
  dangerActionButton: {
    backgroundColor: '#7d2123',
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  dangerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(237, 66, 69, 0.1)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(237, 66, 69, 0.3)',
    marginBottom: 12,
  },
  deleteButton: {
    backgroundColor: 'rgba(237, 66, 69, 0.2)',
    borderColor: 'rgba(237, 66, 69, 0.5)',
  },
  dangerButtonText: {
    color: '#ed4245',
    marginLeft: 8,
    fontWeight: '500',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: Colors.backgroundColor,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    width: '100%',
    maxHeight: '90%',
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#2f3136',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#202225',
  },
  modalHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalTitle: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  modalCloseButton: {
    padding: 4,
  },
  modalBody: {
    padding: 16,
    maxHeight: '70%',
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#202225',
  },
  formGroup: {
    marginBottom: 20,
  },
  formLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  formLabel: {
    color: '#dcddde',
    fontSize: 15,
    fontWeight: '500',
    marginLeft: 8,
  },
  formInput: {
    backgroundColor: '#40444b',
    color: '#dcddde',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
  },
  formDivider: {
    height: 1,
    backgroundColor: '#202225',
    marginVertical: 16,
  },
  cancelButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#4f545c',
  },
  cancelButtonText: {
    color: '#dcddde',
    fontSize: 15,
    fontWeight: '500',
  },
  createButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    minWidth: 140,
  },
  disabledButton: {
    backgroundColor: 'rgba(114, 137, 218, 0.5)',
  },
  createButtonText: {
    color: Colors.white,
    marginLeft: 8,
    fontSize: 15,
    fontWeight: '500',
  },
  inviteLinkContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#40444b',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  inviteLink: {
    flex: 1,
    color: Colors.primary,
    fontSize: 14,
  },
  inviteLinkHint: {
    color: '#8e9297',
    fontSize: 13,
    marginTop: 8,
    fontStyle: 'italic',
  },
  copyButton: {
    backgroundColor: Colors.primary,
    padding: 8,
    borderRadius: 4,
  },
  sendInviteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 16,
  },
  sendInviteText: {
    color: Colors.white,
    marginLeft: 8,
    fontSize: 15,
    fontWeight: '500',
  },
  visibilityCheckmark: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: Colors.primary,
    borderRadius: 10,
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  visibilityDescription: {
    color: '#8e9297',
    fontSize: 13,
    marginTop: 8,
    fontStyle: 'italic',
  },
  recentInvitesList: {
    backgroundColor: '#2f3136',
    borderRadius: 8,
    overflow: 'hidden',
  },
  recentInviteItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#202225',
  },
  recentInviteInfo: {
    flex: 1,
  },
  recentInviteEmail: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: '500',
  },
  recentInviteStatus: {
    color: '#8e9297',
    fontSize: 12,
    marginTop: 4,
  },
  recentInviteAction: {
    padding: 8,
  },
  // Styles pour le modal de confirmation
  confirmModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmModalContent: {
    backgroundColor: Colors.backgroundColor,
    borderRadius: 8,
    width: '90%',
    maxWidth: 400,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  confirmModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2f3136',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#202225',
  },
  confirmModalTitle: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  confirmModalBody: {
    padding: 16,
  },
  confirmModalText: {
    color: '#dcddde',
    fontSize: 16,
    marginBottom: 12,
    lineHeight: 22,
  },
  confirmModalHighlight: {
    color: Colors.white,
    fontWeight: 'bold',
  },
  confirmModalSubtext: {
    color: '#8e9297',
    fontSize: 14,
    fontStyle: 'italic',
  },
  confirmModalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#202225',
  },
  confirmCancelButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#4f545c',
    marginRight: 12,
  },
  confirmCancelButtonText: {
    color: '#dcddde',
    fontSize: 14,
    fontWeight: '500',
  },
  confirmDeleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ED4245',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 4,
  },
  confirmDeleteButtonText: {
    color: Colors.white,
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '500',
  },
  // Styles pour l'édition des informations du workspace
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(114, 137, 218, 0.1)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
    marginLeft: 'auto',
  },
  editButtonText: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 6,
  },
  editActions: {
    flexDirection: 'row',
    marginLeft: 'auto',
  },
  editActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
    marginLeft: 8,
  },
  saveButton: {
    backgroundColor: '#43b581',
  },
  saveButtonText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 4,
  },
  activeInput: {
    borderColor: Colors.primary,
    backgroundColor: 'rgba(114, 137, 218, 0.1)',
  },
  channelDeleteButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(32, 34, 37, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
});

export default styles;
